# Generated by Django 3.0.6 on 2020-05-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
