# Generated by Django 3.0.6 on 2020-05-30 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_assignments'),
        ('assignments', '0002_auto_20200521_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='creation_date',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
