# Generated by Django 3.0.6 on 2020-05-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200521_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assignments',
        ),
    ]
