# Generated by Django 3.0.6 on 2020-05-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_assistant_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'permissions': (('is_assistant', 'Check if is assistant'),)},
        ),
    ]
