# Generated by Django 3.0.6 on 2020-05-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200521_1932'),
        ('assistants', '0003_auto_20200527_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
